name = 'shrty-backend'
main = 'src/index.ts'
compatibility_date = '2026-07-24'

[[kv_namespaces]]
binding="KV"
id="KV_ID"
preview_id="KV_PREVIEW_ID"

[[vars]]
SHORT_DOMAIN="DOMAIN"

[[routes]]
pattern="www.kotoha.de5.net/api/*"
zone_name="kotoha.de5.net"